namespace Packt.Shared;

// this file simulates an autogenerated class
public partial class Person
{
    // a readonly property defined using C# 1 - 5 syntax
    public string Origin
    {
        get
        {
            return string.Format("{0} was born on {1}",
                arg0: Name, arg1: HomePlanet);
        }
    }
    public string Greeting => $"{Name} says 'Hello!'";
    public int Age => CalculateAge(DateOfBirth);

    private int CalculateAge(DateTime birthdate)
    {
        var today = DateTime.Today;
        var age = today.Year - birthdate.Year;
        if (birthdate.Date > today.AddYears(-age)) age--;
        return age;
    }
}